# AUTO-GENERATED by privacykey/privacytracker macos-release workflow.
# Manual edits will be overwritten on the next release.
cask "privacytracker" do
  arch arm: "aarch64", intel: "x64"

  version "0.1.2"
  sha256 arm:   "98999f1f50d7bdec43cbc7933d8957f15b51f556ff6a7983f77d0c8c81d234f6",
         intel: "939d899cd2504814c02a1f3300c82ba601e6db552a19c374faa7310497b76ec9"

  url "https://github.com/privacykey/privacytracker/releases/download/v#{version}/privacytracker_#{version}_#{arch}.dmg",
      verified: "github.com/privacykey/privacytracker/"
  name "privacytracker"
  desc "Monitor, track, and get alerted when iOS apps change their privacy labels"
  homepage "https://github.com/privacykey/privacytracker"

  livecheck do
    url :url
    strategy :github_latest
  end

  auto_updates true
  depends_on macos: :big_sur

  app "privacytracker.app"

  zap trash: [
    "~/Library/Application Support/privacytracker",
    "~/Library/Caches/org.privacykey.privacytracker",
    "~/Library/HTTPStorages/org.privacykey.privacytracker",
    "~/Library/HTTPStorages/org.privacykey.privacytracker.binarycookies",
    "~/Library/Preferences/org.privacykey.privacytracker.plist",
    "~/Library/Saved Application State/org.privacykey.privacytracker.savedState",
    "~/Library/WebKit/org.privacykey.privacytracker",
  ]
end
