# AUTO-GENERATED by privacykey/mantis cli-release workflow.
# Manual edits will be overwritten on the next release.
class Mantis < Formula
  desc "Command-line client for Mantis — manage keys and watch hits from the terminal"
  homepage "https://github.com/privacykey/mantis"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/privacykey/mantis/releases/download/cli-v#{version}/mantis-darwin-arm64.tar.gz"
      sha256 "57e6345d685d2154b256fe312e01e2d49e160a6a4b88985e0c2daf24d798801c"
    end
    on_intel do
      url "https://github.com/privacykey/mantis/releases/download/cli-v#{version}/mantis-darwin-x64.tar.gz"
      sha256 "3669815cc19e8c95130677384e7fff3ebdd4b76c5169fc120c0c9ead52e7cf01"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/privacykey/mantis/releases/download/cli-v#{version}/mantis-linux-arm64.tar.gz"
      sha256 "800c03f7589cb97f9307381a0db352b9d4e98d8a4f19ea15d075fef3ad8af927"
    end
    on_intel do
      url "https://github.com/privacykey/mantis/releases/download/cli-v#{version}/mantis-linux-x64.tar.gz"
      sha256 "4e2737b8f501b30ef0aff4d1bbae3cf079208e8aa3de04254225a9b7324b112e"
    end
  end

def install
    bin.install "mantis"

    # Shell completions — `mantis completion <shell>` writes a ready-to-source
    # script. Homebrew adds these directories to fpath / bash-completion / fish
    # completion path automatically.
    (bash_completion/"mantis").write Utils.safe_popen_read(bin/"mantis", "completion", "bash")
    (zsh_completion/"_mantis").write Utils.safe_popen_read(bin/"mantis", "completion", "zsh")
    (fish_completion/"mantis.fish").write Utils.safe_popen_read(bin/"mantis", "completion", "fish")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mantis --version")
    assert_match "#compdef mantis", (zsh_completion/"_mantis").read
  end
end
