# AUTO-GENERATED by privacykey/mantis cli-release workflow.
# Manual edits will be overwritten on the next release.
class Mantis < Formula
  desc "Command-line client for Mantis — manage keys and watch hits from the terminal"
  homepage "https://github.com/privacykey/mantis"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/privacykey/mantis/releases/download/cli-v#{version}/mantis-darwin-arm64.tar.gz"
      sha256 "ad1d85db7285be988fa0c20cfb06dde71255ee7a92c134bbdefce7884e1ab239"
    end
    on_intel do
      url "https://github.com/privacykey/mantis/releases/download/cli-v#{version}/mantis-darwin-x64.tar.gz"
      sha256 "f9075a02f4abf072a7015fb71ec2c7e804d500205541d086154527787706ea8d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/privacykey/mantis/releases/download/cli-v#{version}/mantis-linux-arm64.tar.gz"
      sha256 "bb1b91d21b84f17ef4e898fc416507ef509d7dff457ea43dc2daf511b1846ae2"
    end
    on_intel do
      url "https://github.com/privacykey/mantis/releases/download/cli-v#{version}/mantis-linux-x64.tar.gz"
      sha256 "12cbde1e3ebdf34836b19586ffc7af1d274139a8591ff13cd8053de4296ca549"
    end
  end

  def install
    bin.install "mantis"
    man1.install "share/man/man1/mantis.1"

    # Shell completions — `mantis completion <shell>` writes a ready-to-source
    # script; the DSL runs it once per shell and installs the output under
    # bash-completion / fpath / fish's completion path.
    generate_completions_from_executable(bin/"mantis", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mantis --version")
    assert_match "#compdef mantis", (zsh_completion/"_mantis").read
    assert_match "MANTIS 1", (man1/"mantis.1").read
  end
end
