# AUTO-GENERATED by privacykey/mantis cli-release workflow.
# Manual edits will be overwritten on the next release.
class Mantis < Formula
  desc "Command-line client for Mantis — manage keys and watch hits from the terminal"
  homepage "https://github.com/privacykey/mantis"
  version "0.2.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/privacykey/mantis/releases/download/cli-v#{version}/mantis-darwin-arm64.tar.gz"
      sha256 "74b03697f07a313a4666f485d97608dcfb52a11cd73adea9d526027716b3746d"
    end
    on_intel do
      url "https://github.com/privacykey/mantis/releases/download/cli-v#{version}/mantis-darwin-x64.tar.gz"
      sha256 "80ad739e6fe8914adcfa9e05a9fca0e5c77673bd778291d672914a2ee232a064"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/privacykey/mantis/releases/download/cli-v#{version}/mantis-linux-arm64.tar.gz"
      sha256 "7073b0ae6486efc34f3128f12933344c6bcf1619c45045f30f7f244250f855e5"
    end
    on_intel do
      url "https://github.com/privacykey/mantis/releases/download/cli-v#{version}/mantis-linux-x64.tar.gz"
      sha256 "ef58fb4fed50d4364f8fcd5dd68554409c5fecaf2788ef19a3c5c27e26b89d37"
    end
  end

  def install
    bin.install "mantis"
    man1.install "share/man/man1/mantis.1"

    # Shell completions — `mantis completion <shell>` writes a ready-to-source
    # script; the DSL runs it once per shell and installs the output under
    # bash-completion / fpath / fish's completion path.
    generate_completions_from_executable(bin/"mantis", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mantis --version")
    assert_match "#compdef mantis", (zsh_completion/"_mantis").read
    assert_match "MANTIS 1", (man1/"mantis.1").read
  end
end
